version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps.github-actions)"
    assignees:
      - "adamperkowski"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps.cargo)"
    assignees:
      - "adamperkowski"
