[package]
name = "website"
version = "0.1.0"
edition = "2021"
license = "MIT AND CC-BY-ND-4.0"
homepage = "https://adamperkowski.dev"
repository = "https://github.com/adamperkowski/adamperkowski.github.io"
authors = ["Adam Perkowski <adas1per@protonmnail.com>"]

[dependencies]
async-stream = "0.3.6"
axum = "0.8.1"
hex = "0.4.3"
hmac = "0.12.1"
lazy_static = "1.5.0"
mime_guess = "2.0.5"
rust-embed = { version = "8.6.0", features = ["include-exclude", "compression"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.8"
tera = { version = "1.20.0", default-features = false }
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.17", default-features = false }
