[package]
name = "website"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-MIT-WITH-Happy-Bunny OR MIT"
homepage = "https://adamperkowski.dev"
repository = "https://github.com/adamperkowski/website"
authors = ["Adam Perkowski <adas1per@protonmnail.com>"]

[dependencies]
axum = { version = "0.8.6", default-features = false }
shuttle-axum = "0.57.0"
shuttle-runtime = "0.57.0"
