[package]
name = "website"
version = "0.1.0"
edition = "2021"
license = "MIT AND CC-BY-ND-4.0"
homepage = "https://adamperkowski.dev"
repository = "https://github.com/adamperkowski/adamperkowski.github.io"
authors = ["Adam Perkowski <adas1per@protonmnail.com>"]

[dependencies]
lazy_static = "1.5.0"
rust-embed = { version = "8.7.0", features = ["include-exclude", "compression"] }
serde = { version = "1.0.219", features = ["derive"] }
tera = { version = "1.20.0", default-features = false }
