name: Tests & Checks

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run FMT
        run: cargo fmt --all --check

      - name: Run Clippy
        run: cargo clippy -- -Dwarnings

  typos:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for typos in content
        uses: crate-ci/typos@master
        with:
          files: ./content

      - name: Check for typos in templates
        uses: crate-ci/typos@master
        with:
          files: ./templates
